joint_state_publisher:
    ros__parameters:
        use_sim_time: True
        use_gui: True
        rate: 50
        publish_default_velocities: True
        publish_default_efforts: True
        robot_description: ''
        source_list: ['joint_states_sim']

robot_state_publisher:
    ros__parameters:
        use_sim_time: True
        robot_description: ''
        ignore_timestamp: False